# Generated by ChatGPT on 2026-01-29
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_wishlist_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(help_text="Rating from 1 to 5."),
                ),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                ("body", models.TextField()),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="If false, the review is hidden from public endpoints until moderated.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"), name="uniq_review_user_item"
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["item", "is_approved", "created_at"],
                        name="idx_review_item_appr_created",
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="idx_review_user_created"
                    ),
                ],
            },
        ),
    ]
